# AIM-5001 WEEK 4 Assignment

1. (5 Points) Write a Python/NumPy code block that finds the distinct/unique common items between these two arrays:
a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])
Your output should contain only the distinct overlapping values. For example, if a 2 is found in both array a and array b, your output should contain only one 2 even if array a contains more than one 2 within it.

* np has a function to get the intersection values of 2 arrays without overlapping, np.intersect1d().

In [1]:
import numpy as np
a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6]) 
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])

# get commom items from a and b
q1=np.intersect1d(a,b)
print(q1)

[2 4]


2. (5 Points) Create the following 5x3 array using knowledge you have of Python’s / NumPy’s sequencing functionality so that you do not need to explicitly key in every integer value.

* Create an array with numbers from 1 to 15, then use reshape function to  shape it to 5x3, transpose it.

In [2]:
import numpy as np

# create the array from 1 to 15. reshape and transpose 
q2=np.arange(1,16).reshape(3,5).T
print(q2)

[[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]


3. (5 Points) You are given the following two arrays:
a = np.array([12, 5, 7, 15, 3, 1, 8])
b = np.array([14, 6, 3, 11, 19, 12, 5])
Write a Python/Numpy code block that removes from array a any items that are also present in array b.

* Use np.isin(a,b) to get the boolean values when elements in b also found in a, get the index by np.where(), then remove the common items with np.delete().

In [3]:
import numpy as np

a = np.array([12, 5, 7, 15, 3, 1, 8]) 
b = np.array([14, 6, 3, 11, 19, 12, 5])

# get index of elements in a also in b
c=np.where(np.isin(a,b))
# remove the common items from a
q3=np.delete(a,c)
print(q3)

[ 7 15  1  8]


4. (7 Points) Suppose you have ridden a bicycle from New York City to Key West, Florida. Your bicycle odometer shows the total miles you have travelled thus far, which you make a note of each day with paper and pencil. Your first two entries might be ‘55’ and ‘120’, indicating that you rode your bike 55 miles on day 1 and 65 miles on day 2. Your task is to create a NumPy array wherein you can record the cumulative miles you recorded each day during your trip “by hand”. Then use your Python skills to show the total miles that you rode each day. Assume the trip took a total of 35 days and included at least 4 non-consecutive days where no cycling was possible due to either weather conditions or personal fatigue/soreness. For the remaining 31 days, you would have covered the entire distance between NYC and Key West. Complete your work within your Jupyter Notebook for this assignment and be sure to include a writeup explaining your approach to this problem, including the ways in which you decided to make use of NumPy.

* From day 0, I began to record the odometer and put the record in a list. Use the following value deduct the previous value will be the distance I rode and stored it in a numpy array. Using numpy array cane be easier to do the substraction if the values are at the correspondent position, which means if the array can apply substraction on values having the same index. It can be implement by 2 ways. The first is doing misplaced substraction. The second will be using following value substracting previous value.

In [4]:
#store all odometer record in the list
byhand=[0,55,120,175,226,280,317,364,402,460,503,503,542,587,635,680,722,787,824,859,901,952,991,1032,
        1063,1063,1127,1182,1225,1225,1285,1356,1415,1469,1469,1520]

import numpy as np
# Way1: set 2 arrays from day0 to day34, and day1 to day35
arr1=np.array(byhand[:-1])
arr2=np.array(byhand[1:])

# store each day distance in q4a
q4a=np.array(arr2-arr1)
print (q4a)

[55 65 55 51 54 37 47 38 58 43  0 39 45 48 45 42 65 37 35 42 51 39 41 31
  0 64 55 43  0 60 71 59 54  0 51]


In [5]:
# Way2: simply use the following value minus previous value
q4b=np.diff(byhand)
print (q4b)

[55 65 55 51 54 37 47 38 58 43  0 39 45 48 45 42 65 37 35 42 51 39 41 31
  0 64 55 43  0 60 71 59 54  0 51]


5.Using the NumPy array that has been loaded for you in the Jupyter Notebook, answer the following questions using NumPy’s slicing, methods, and functions:

 What is the maximum yearly NYC consumption of water in millions of gallons per day? 

 How many calendar years are represented within this data set? NumPy's shape command is one way to find out. 

 What is the mean and the standard deviation of the per capita daily water consumption?  

 What is the increase or decrease in population from year to year? 

Use NumPy's `diff` function to create an array of differences and save that to a variable called "pop_diff", then print that variable to the screen.

* Import the csv file and use np.max() get the maximum value, use np.shape() to know the days of dataset, use np.mean() and np.std() to get the mean and standard deviation, use np.diff() to calculate the population increase.

In [6]:
import pandas
import numpy as np

# supress scientific notation
np.set_printoptions(suppress = True)

# read the data file from GitHub and convert to a NumPy ndarray object
nyc_water = pandas.read_csv('https://raw.githubusercontent.com/jtopor/DAV-5400/master/Week4/Water_Consumption_In_The_New_York_City.csv').values


# verify you have an ndarray object
type(nyc_water)


numpy.ndarray

In [7]:
# the maxinum of the 3rd column NYC Consumption(Million gallons per day).

maximum=np.max(nyc_water[:,2])
print("The maximum yearly NYC consumption of water in millions of gallons per day is "+str(maximum)+".")

The maximum yearly NYC consumption of water in millions of gallons per day is 1512.0.


In [8]:
# use shape to get how many rows means how many years, assign row value to a.

a,b=nyc_water.shape
print (str(a)+" calendar years are represented within this data set.")

39 calendar years are represented within this data set.


In [9]:
# The per capita daily water consumption is the 4th column, Per Capita(Gallons per person per day).

mean=round(np.mean(nyc_water[:,3]),2)
std=round(np.std(nyc_water[:,3]),2)
print("The mean and the standard deviation of the per capita daily water consumption are "+str(mean)+" Gallons and "+str(std)+".")

The mean and the standard deviation of the per capita daily water consumption are 160.31 Gallons and 31.52.


In [10]:
# Use np.differ() to apply on the 2nd column, New York City Population.

pop_diff=np.diff(nyc_water[:,1])
print(pop_diff)

[-30461.   17602.   19864.   72119.   53290.   39540.   45192.   23230.
  11243.   -9544.   -8525.   38851.   54443.   77222.   64292.   62582.
  64772.   75631.   84816.   89401.   60618.   16685.5  16685.5  16685.5
  16685.5  16685.5  16685.5  16685.5  16685.5  16685.5  16685.5 108965.
  77081.   61281.   49530.   44512.   21171.   85025. ]
